"""empty message

Revision ID: 4245e71e18aa
Revises: a92e8190bf39
Create Date: 2025-09-16 23:42:01.507191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4245e71e18aa'
down_revision = 'a92e8190bf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash_hash',
                            sa.String(length=255), nullable=False))
        batch_op.drop_column('contraseña_hash_hash')

    with op.batch_alter_table('analista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash_hash',
                            sa.String(length=255), nullable=False))
        batch_op.drop_column('contraseña_hash_hash')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash_hash',
                            sa.String(length=255), nullable=False))
        batch_op.drop_column('contraseña_hash_hash')

    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash_hash',
                            sa.String(length=255), nullable=False))
        batch_op.drop_column('contraseña_hash_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash_hash', sa.VARCHAR(
            length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('contraseña_hash_hash')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash_hash', sa.VARCHAR(
            length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('contraseña_hash_hash')

    with op.batch_alter_table('analista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash_hash', sa.VARCHAR(
            length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('contraseña_hash_hash')

    with op.batch_alter_table('administrador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash_hash', sa.VARCHAR(
            length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('contraseña_hash_hash')

    # ### end Alembic commands ###
