"""empty message

Revision ID: 71258b9a123d
Revises: a80e12f7bf60
Create Date: 2025-09-17 22:44:53.960783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71258b9a123d'
down_revision = 'a80e12f7bf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
