"""empty message

Revision ID: e130f08b253b
Revises: 3a7d6f3dde80
Create Date: 2025-09-14 22:54:25.370492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e130f08b253b'
down_revision = '3a7d6f3dde80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_analista', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('id_analista')

    # ### end Alembic commands ###
