"""empty message

Revision ID: f00d90e2b65f
Revises: 71258b9a123d
Create Date: 2025-09-19 17:00:06.663180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f00d90e2b65f'
down_revision = '71258b9a123d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('img_urls')

    # ### end Alembic commands ###
